@startuml BUSINESS
|Admin|
start
:Login;
:Manage and Update Application Settings;
:Manage Customer Data;
|Analyst|
:Login;
:Data Management;
:Export Data;
:Customer Segmentation;
fork
    :Predict Customer Segment;
fork again
    :Generate Reports;
endfork
|End User|
:Login;
:Visualize Customer Segmentation;
stop
@enduml
